//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
<<<<<<<< HEAD:ItalianPizza/DatabaseModel/DatabaseMapping/CustomerOrderCustomer.cs
    public partial class CustomerOrderCustomer
========
    public partial class CustomerOrderCustomerSet
>>>>>>>> d1b5b603a1726b12cc340c733b91b809aceecd0d:ItalianPizza/DatabaseModel/DatabaseMapping/CustomerOrderCustomerSet.cs
    {
        public int Id { get; set; }
        public int CustomerOrderId { get; set; }
        public int CustomerId { get; set; }
    
<<<<<<<< HEAD:ItalianPizza/DatabaseModel/DatabaseMapping/CustomerOrderCustomer.cs
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual Customer Customer { get; set; }
========
        public virtual CustomerSet CustomerSet { get; set; }
        public virtual CustomerOrderSet CustomerOrderSet { get; set; }
>>>>>>>> d1b5b603a1726b12cc340c733b91b809aceecd0d:ItalianPizza/DatabaseModel/DatabaseMapping/CustomerOrderCustomerSet.cs
    }
}
