//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOrderSet()
        {
            this.CustomerOrderDetailSet = new HashSet<CustomerOrderDetailSet>();
            this.CustomerSet = new HashSet<CustomerSet>();
            this.DeliveryDriverSet = new HashSet<DeliveryDriverSet>();
            this.FinancialTransactionSet = new HashSet<FinancialTransactionSet>();
        }
    
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double TotalAmount { get; set; }
        public System.TimeSpan RegistrationTime { get; set; }
        public int OrderStatusId { get; set; }
        public int OrderTypeId { get; set; }
        public int EmployeeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrderDetailSet> CustomerOrderDetailSet { get; set; }
        public virtual EmployeeSet EmployeeSet { get; set; }
        public virtual OrderStatusSet OrderStatusSet { get; set; }
        public virtual OrderTypeSet OrderTypeSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSet> CustomerSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryDriverSet> DeliveryDriverSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialTransactionSet> FinancialTransactionSet { get; set; }
    }
}
