//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderDeliveryDriverSet
    {
        public int Id { get; set; }
        public int CustomerOrderId { get; set; }
        public int DeliveryDriverId { get; set; }
    
        public virtual CustomerOrderSet CustomerOrderSet { get; set; }
        public virtual DeliveryDriverSet DeliveryDriverSet { get; set; }
    }
}
