//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
<<<<<<<< HEAD:ItalianPizza/DatabaseModel/DatabaseMapping/CustomerOrderDeliveryDriver.cs
    public partial class CustomerOrderDeliveryDriver
========
    public partial class CustomerOrderDeliveryDriverSet
>>>>>>>> d1b5b603a1726b12cc340c733b91b809aceecd0d:ItalianPizza/DatabaseModel/DatabaseMapping/CustomerOrderDeliveryDriverSet.cs
    {
        public int Id { get; set; }
        public int CustomerOrderId { get; set; }
        public int DeliveryDriverId { get; set; }
    
<<<<<<<< HEAD:ItalianPizza/DatabaseModel/DatabaseMapping/CustomerOrderDeliveryDriver.cs
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual DeliveryDriver DeliveryDriver { get; set; }
========
        public virtual CustomerOrderSet CustomerOrderSet { get; set; }
        public virtual DeliveryDriverSet DeliveryDriverSet { get; set; }
>>>>>>>> d1b5b603a1726b12cc340c733b91b809aceecd0d:ItalianPizza/DatabaseModel/DatabaseMapping/CustomerOrderDeliveryDriverSet.cs
    }
}
