//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItalianPizzaServerBDEntities : DbContext
    {
        public ItalianPizzaServerBDEntities()
            : base("name=ItalianPizzaServerBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Producto> ProductoSet { get; set; }
        public virtual DbSet<OrdenCliente> OrdenClienteSet { get; set; }
        public virtual DbSet<Empleado> EmpleadoSet { get; set; }
        public virtual DbSet<Proveedor> ProveedorSet { get; set; }
        public virtual DbSet<Cliente> ClienteSet { get; set; }
        public virtual DbSet<Dirección> DirecciónSet { get; set; }
        public virtual DbSet<Repartidor> RepartidorSet { get; set; }
        public virtual DbSet<Insumo> InsumoSet { get; set; }
        public virtual DbSet<PedidoProveedor> PedidoProveedorSet { get; set; }
        public virtual DbSet<CorteDiario> CorteDiarioSet { get; set; }
        public virtual DbSet<ValidacionInventario> ValidacionInventarioSet { get; set; }
        public virtual DbSet<Cuenta> CuentaSet { get; set; }
        public virtual DbSet<OrdenClienteDetalle> OrdenClienteDetalleSet { get; set; }
        public virtual DbSet<PedidoProveedorDetalle> PedidoProveedorDetalleSet { get; set; }
    }
}
