//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDriverSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryDriverSet()
        {
<<<<<<< HEAD
            this.CustomerOrderSet = new HashSet<CustomerOrderSet>();
=======
            this.CustomerOrderDeliveryDriverSet = new HashSet<CustomerOrderDeliveryDriverSet>();
>>>>>>> d1b5b603a1726b12cc340c733b91b809aceecd0d
        }
    
        public int Id { get; set; }
        public string Names { get; set; }
        public string LastName { get; set; }
        public string SecondLastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int EmployeeId { get; set; }
        public int UserStatusId { get; set; }
    
<<<<<<< HEAD
        public virtual EmployeeSet EmployeeSet { get; set; }
        public virtual UserStatusSet UserStatusSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrderSet> CustomerOrderSet { get; set; }
=======
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrderDeliveryDriverSet> CustomerOrderDeliveryDriverSet { get; set; }
        public virtual EmployeeSet EmployeeSet { get; set; }
        public virtual UserStatusSet UserStatusSet { get; set; }
>>>>>>> d1b5b603a1726b12cc340c733b91b809aceecd0d
    }
}
