//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeSet()
        {
            this.CustomerOrderSet = new HashSet<CustomerOrderSet>();
            this.CustomerSet = new HashSet<CustomerSet>();
            this.DailyClosingSet = new HashSet<DailyClosingSet>();
            this.DeliveryDriverSet = new HashSet<DeliveryDriverSet>();
            this.FinancialTransactionSet = new HashSet<FinancialTransactionSet>();
            this.InventoryValidationSet = new HashSet<InventoryValidationSet>();
            this.ProductSaleSet = new HashSet<ProductSaleSet>();
            this.RecipeSet = new HashSet<RecipeSet>();
            this.SupplierSet = new HashSet<SupplierSet>();
            this.SupplierOrderSet = new HashSet<SupplierOrderSet>();
            this.SupplySet = new HashSet<SupplySet>();
            this.EmployeePictureSet = new HashSet<EmployeePictureSet>();
        }
    
        public int Id { get; set; }
        public string Names { get; set; }
        public string LastName { get; set; }
        public string SecondLastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public byte[] ProfilePhoto { get; set; }
        public int UserStatusId { get; set; }
        public int EmployeePositionId { get; set; }
        public int Address_Id { get; set; }
        public int UserAccount_Id { get; set; }
    
        public virtual AddressSet AddressSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrderSet> CustomerOrderSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSet> CustomerSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyClosingSet> DailyClosingSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryDriverSet> DeliveryDriverSet { get; set; }
        public virtual EmployeePositionSet EmployeePositionSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialTransactionSet> FinancialTransactionSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryValidationSet> InventoryValidationSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSaleSet> ProductSaleSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeSet> RecipeSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierSet> SupplierSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierOrderSet> SupplierOrderSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplySet> SupplySet { get; set; }
        public virtual UserAccountSet UserAccountSet { get; set; }
        public virtual UserStatusSet UserStatusSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePictureSet> EmployeePictureSet { get; set; }
    }
}
