//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialTransactionSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialTransactionSet()
        {
            this.DailyClosingSet = new HashSet<DailyClosingSet>();
            this.CustomerOrderSet = new HashSet<CustomerOrderSet>();
            this.SupplierOrderSet = new HashSet<SupplierOrderSet>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public System.DateTime FinancialTransactionDate { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<double> MonetaryValue { get; set; }
        public string Context { get; set; }
    
        public virtual EmployeeSet EmployeeSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyClosingSet> DailyClosingSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrderSet> CustomerOrderSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierOrderSet> SupplierOrderSet { get; set; }
    }
}
