//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeFinancialTransactionSet
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime RealizationDate { get; set; }
        public double MonetaryValue { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> FinancialTransactionIncomeContextId { get; set; }
        public Nullable<int> DailyClosingId { get; set; }
    
        public virtual DailyClosingSet DailyClosingSet { get; set; }
        public virtual EmployeeSet EmployeeSet { get; set; }
        public virtual FinancialTransactionIncomeContextSet FinancialTransactionIncomeContextSet { get; set; }
    }
}
