//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItalianPizzaServerBDEntities : DbContext
    {
        public ItalianPizzaServerBDEntities()
            : base("name=ItalianPizzaServerBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<CorteDiarioSet> CorteDiarioSet { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Dirección> Dirección { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Insumo> Insumo { get; set; }
        public virtual DbSet<OrdenCliente> OrdenCliente { get; set; }
        public virtual DbSet<OrdenClienteDetalle> OrdenClienteDetalle { get; set; }
        public virtual DbSet<PedidoProveedorDetalleSet> PedidoProveedorDetalleSet { get; set; }
        public virtual DbSet<PedidoProveedorSet> PedidoProveedorSet { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<ProveedorSet> ProveedorSet { get; set; }
        public virtual DbSet<RepartidorSet> RepartidorSet { get; set; }
        public virtual DbSet<ValidacionInventarioSet> ValidacionInventarioSet { get; set; }
    }
}
