//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenClienteDetalle
    {
        public int Id { get; set; }
        public int OrdenClienteId { get; set; }
        public int ProductoId { get; set; }
        public string CantidadProducto { get; set; }
        public string CostoProducto { get; set; }
    
        public virtual OrdenCliente OrdenCliente { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
