//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoProveedorDetalleSet
    {
        public int Id { get; set; }
        public int PedidoProveedorId { get; set; }
        public int InsumoId { get; set; }
        public string CantidadInsumo { get; set; }
        public string CostoInsumo { get; set; }
    
        public virtual Insumo Insumo { get; set; }
        public virtual PedidoProveedorSet PedidoProveedorSet { get; set; }
    }
}
