//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSaleSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSaleSet()
        {
            this.CustomerOrderDetailSet = new HashSet<CustomerOrderDetailSet>();
            this.RecipeSet = new HashSet<RecipeSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public double PricePerUnit { get; set; }
        public byte[] Picture { get; set; }
        public int ProductStatusId { get; set; }
        public int ProductTypeId { get; set; }
        public int EmployeeId { get; set; }
        public string IdentificationCode { get; set; }
        public string Description { get; set; }
        public string Observations { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrderDetailSet> CustomerOrderDetailSet { get; set; }
        public virtual EmployeeSet EmployeeSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeSet> RecipeSet { get; set; }
        public virtual ProductStatusSet ProductStatusSet { get; set; }
        public virtual ProductTypeSet ProductTypeSet { get; set; }
    }
}
