//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecipeSet()
        {
            this.RecipeDetailsSet = new HashSet<RecipeDetailsSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Instructions { get; set; }
        public string Status { get; set; }
        public int EmployeeId { get; set; }
        public int ProductSale_Id { get; set; }
    
        public virtual EmployeeSet EmployeeSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeDetailsSet> RecipeDetailsSet { get; set; }
        public virtual ProductSaleSet ProductSaleSet { get; set; }
    }
}
