//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrderSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierOrderSet()
        {
            this.SupplierOrderDetailsSet = new HashSet<SupplierOrderDetailsSet>();
            this.FinancialTransactionSet = new HashSet<FinancialTransactionSet>();
        }
    
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double TotalAmount { get; set; }
        public System.TimeSpan RegistrationTime { get; set; }
        public int OrderStatusId { get; set; }
        public int EmployeeId { get; set; }
        public int Supplier_Id { get; set; }
    
        public virtual EmployeeSet EmployeeSet { get; set; }
        public virtual OrderStatusSet OrderStatusSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierOrderDetailsSet> SupplierOrderDetailsSet { get; set; }
        public virtual SupplierSet SupplierSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialTransactionSet> FinancialTransactionSet { get; set; }
    }
}
