//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
<<<<<<<< HEAD:ItalianPizza/DatabaseModel/DatabaseMapping/SupplierOrder.cs
    public partial class SupplierOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierOrder()
        {
            this.SupplierOrderDetails = new HashSet<SupplierOrderDetails>();
            this.FinancialTransaction = new HashSet<FinancialTransaction>();
========
    public partial class SupplierOrderSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierOrderSet()
        {
            this.SupplierOrderDetailsSet = new HashSet<SupplierOrderDetailsSet>();
            this.FinancialTransactionSet = new HashSet<FinancialTransactionSet>();
>>>>>>>> d1b5b603a1726b12cc340c733b91b809aceecd0d:ItalianPizza/DatabaseModel/DatabaseMapping/SupplierOrderSet.cs
        }
    
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double TotalAmount { get; set; }
        public System.TimeSpan RegistrationTime { get; set; }
        public int OrderStatusId { get; set; }
        public int EmployeeId { get; set; }
<<<<<<<< HEAD:ItalianPizza/DatabaseModel/DatabaseMapping/SupplierOrder.cs
    
        public virtual Supplier Supplier { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierOrderDetails> SupplierOrderDetails { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialTransaction> FinancialTransaction { get; set; }
========
        public int Supplier_Id { get; set; }
    
        public virtual EmployeeSet EmployeeSet { get; set; }
        public virtual OrderStatusSet OrderStatusSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierOrderDetailsSet> SupplierOrderDetailsSet { get; set; }
        public virtual SupplierSet SupplierSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialTransactionSet> FinancialTransactionSet { get; set; }
>>>>>>>> d1b5b603a1726b12cc340c733b91b809aceecd0d:ItalianPizza/DatabaseModel/DatabaseMapping/SupplierOrderSet.cs
    }
}
