//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel.DatabaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyPictureSet
    {
        public int Id { get; set; }
        public byte[] SupplyImage { get; set; }
        public int Supply_Id { get; set; }
    
        public virtual SupplySet SupplySet { get; set; }
    }
}
