//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItalianPizzaServerBDEntities : DbContext
    {
        public ItalianPizzaServerBDEntities()
            : base("name=ItalianPizzaServerBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Supplier> SupplierSet { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<OrderCustomer> OrderCustomerSet { get; set; }
        public virtual DbSet<Recipe> RecipeSet { get; set; }
        public virtual DbSet<SupplierOrder> SupplierOrderSet { get; set; }
        public virtual DbSet<Supply> SupplySet { get; set; }
        public virtual DbSet<OrderCustomerProduct> OrderCustomerProductSet { get; set; }
        public virtual DbSet<Customer> CustomerSet { get; set; }
        public virtual DbSet<SupplierOrderSupply> SupplierOrderSupplySet { get; set; }
        public virtual DbSet<RecipeSupply> RecipeSupplySet { get; set; }
        public virtual DbSet<Employee> EmployeeSet { get; set; }
        public virtual DbSet<EmployeeRole> EmployeeRoleSet { get; set; }
        public virtual DbSet<Address> AddressSet { get; set; }
        public virtual DbSet<SupplierSupply> SupplierSupplySet { get; set; }
        public virtual DbSet<Dealer> DealerSet { get; set; }
        public virtual DbSet<DealerOrderCustomer> DealerOrderCustomerSet { get; set; }
    }
}
