//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderCustomer()
        {
            this.OrderCustomerProduct = new HashSet<OrderCustomerProduct>();
            this.DealerOrderCustomer = new HashSet<DealerOrderCustomer>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double TotalCost { get; set; }
        public int EmployeeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCustomerProduct> OrderCustomerProduct { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerOrderCustomer> DealerOrderCustomer { get; set; }
    }
}
