//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderCustomerProduct = new HashSet<OrderCustomerProduct>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public short Cost { get; set; }
        public short Amount { get; set; }
        public int EmployeeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCustomerProduct> OrderCustomerProduct { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
