//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPizza.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrderSupply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierOrderSupply()
        {
            this.Supply = new HashSet<Supply>();
            this.SupplierOrder = new HashSet<SupplierOrder>();
        }
    
        public int Id { get; set; }
        public double IndividualSupplyCost { get; set; }
        public short SupplyCount { get; set; }
        public int SupplyID { get; set; }
        public int OrderSupplierID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierOrder> SupplierOrder { get; set; }
    }
}
